//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fight
    {
        public int Id { get; set; }
        public int character1 { get; set; }
        public int character2 { get; set; }
        public Nullable<int> winner { get; set; }
        public int teritory_fight { get; set; }
        public int id_war { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Character Character3 { get; set; }
        public virtual Character Character4 { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual War War { get; set; }
    }
}
